platform :ios, ‘9.0’
use_frameworks!

target ‘BayeSocial’ do
    
pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'AliyunOSSiOS', '~> 2.6.2'
pod 'HyphenateLite'
pod 'WebViewJavascriptBridge', '~> 6.0.2'
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git' , :branch => 'swift4'

pod 'SwiftyJSON', '~> 3.1.4'
#pod 'IQKeyboardManagerSwift', :git => 'https://github.com/hackiftekhar/IQKeyboardManager.git' , :branch => 'swift4'
pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher.git' , :branch => 'swift4'

pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift4'
pod 'SnapKit', :git => 'https://github.com/SnapKit/SnapKit.git', :branch => 'swift-4'

pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD.git', :branch => 'release/swift4'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'HandyJSON', :git => 'https://github.com/alibaba/HandyJSON.git' , :branch => 'dev_for_swift4.0'

 pod 'Realm'
 pod 'SDWebImage', '~> 4.0.0'
pod 'CYPhotosKit', '~> 2.7.0'

end

